### ISSUE TITLE
Wrong connection diagram!

### ISSUE THREAD

**Issue by dwillmore** [Kris-Sekula/Pine64_Ox64_SBC#1]
Your wiring diagram is dangerously incorrect!  Pin 40 or 39 can be used for power input, 39 is *not* ground.  The circuit in your diagram will blow the Vbus to Vsystem protection diode and damage boards.  Please change it to use pin 38 as ground and pin 39 as V+.

**Comment by Kris-Sekula** [comment]
Am I blind or something... I focused too much on ensuring RX TX was correctly connected and missed the obvious. I have it connected correctly in the video and on the breadboard, but I "fat-fingered" that GND connection to pin 2 instead of 3 on the diagram. Thanks for pointing out, updated the picture to reflect correct connection.
